name: samba
services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      NAME: "shared"
      USER: "public"
      PASS: "123456"
    ports:
      - 445:445
    volumes:
      - /server/shared:/storage
    restart: always